### PR TITLE
Enhancements: Makefile Introduction, Dockerfile Improvements, and README Updates

### PR DESCRIPTION
**Pull request by arnovandash**
Overview:
This pull request introduces a comprehensive set of enhancements that streamline the build process, improve Docker image handling, and enhance documentation.

Main Changes:

1. Introduced a Makefile:
- Simplified the docker build process with easy-to-use commands.

2. Dockerfile Improvements:
- Updated the base image to debian:bookworm-slim.
- Resolved the missing /etc/mtab issue, ensuring smoother package installations.
- Streamlined the installation of essential dependencies.
- Added a Python installation.
- Added an entrypoint script primarily to address a repo permissions issue and to improve command handling within the Docker container.

3. README Update:
- Reformatted for better readability.
- Updated build instructions, incorporating the Makefile approach.
- Improved clarity on different flavors of the Docker image.
- Updated examples.
- Added build instructions for Varoom3D (Butano)

Benefits:
With these changes, users can expect a more intuitive and smoother experience when setting up their environment, building Docker images, and referencing documentation for assistance.

### CODE REVIEW

**Comment by redthing1** [comment]
This looks pretty good actually, thanks. Any ideas for more or different flavors?

**Comment by arnovandash** [comment]
I was thinking of a lite flavour that only has Python added over the base flavour specifically for Butano projects but I've got no GBA dev experience yet so I don't know what else would be required. For now the dusk flavour has me covered for my personal use, thanks for that.

**Comment by redthing1** [comment]
Sure, I will merge after another review later this week. If I forget feel free to ping me

**Comment by arnovandash** [comment]
Thanks, will do!

**Comment by arnovandash** [comment]
Hey @redthing1. I forgot to nudge you about this. Would be awesome if you could take another peek if you get a moment. Really appreciate your feedback!

**Comment by redthing1** [comment]
Looks good, thanks!

**Comment by redthing1** [comment]
Your help is much appreciated.

**Pull request merged**
